apiVersion: apps/v1
kind: Deployment
metadata:
  name: application1-deployment
  namespace: monitoring
  labels:
    app: application1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application1
  template:
    metadata:
      labels:
        app: ws-screenshot
    spec:
      containers:
      - name: application1
        image: dragonbruceli/prometheus-flask-example
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ws-screenshot-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8000'
spec:
  type: NodePort
  selector:
    app: application1
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 42422