apiVersion: apps/v1
kind: Deployment
metadata:
  name: application2-deployment
  namespace: monitoring
  labels:
    app: application2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
      labels:
        app: application2
    spec:
      containers:
      - name: application2
        image: dragonbruceli/prometheus-not-available-example:1.0.0
        ports:
          - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: application2-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8001'
spec:
  type: NodePort
  selector:
    app: application2
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30034