kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m 
    receivers:
    - name: alert-emailer
      email_configs:
      - to: 'receiver_mail_id@gmail.com'
        from: 'ari.moen@ethereal.email'
        smarthost: smtp.ethereal.email:587
        auth_username: 'ari.moen@ethereal.email'
        auth_identity: 'ari.moen@ethereal.email'
        auth_password: 'TxqGqaDA3g6MQbJkVy'